### ISSUE TITLE
Scheduling View: toggleActivityDay 'split' is null

### ISSUE THREAD

**Issue by cthielen** [ucdavis/ipa-client-angular#1004]
URL: https://ipa.ucdavis.edu/scheduling/11/2017/01

User: Pham, Thao

Kerberos: tpham511

Full Error: Cannot read property 'split' of null

Stack: TypeError: Cannot read property 'split' of null
    at ChildScope.$scope.toggleActivityDay (https://ipa.ucdavis.edu/js/schedulingApp.js?rel=1492190481876:6:4312)
    at fn (eval at compile (https://ipa.ucdavis.edu/js/lib.js:17:3884), <anonymous>:4:346)
    at expensiveCheckFn (https://ipa.ucdavis.edu/js/lib.js:14:932)
    at callback (https://ipa.ucdavis.edu/js/lib.js:18:2963)
    at ChildScope.$eval (https://ipa.ucdavis.edu/js/lib.js:14:19946)
    at ChildScope.$apply (https://ipa.ucdavis.edu/js/lib.js:14:20285)
    at HTMLButtonElement.<anonymous> (https://ipa.ucdavis.edu/js/lib.js:18:3070)
    at HTMLButtonElement.dispatch (https://ipa.ucdavis.edu/js/lib.js:8:12090)
    at HTMLButtonElement.elemData.handle (https://ipa.ucdavis.edu/js/lib.js:8:8982)

**Comment by ltwheeler** [comment]
Issue resolved previously
