### ISSUE TITLE
Instructional Support Call Form: dueDate is null

### ISSUE THREAD

**Issue by cthielen** [ucdavis/ipa-client-angular#1005]
URL: https://ipa.ucdavis.edu/instructionalSupport/67/2018/05/studentSupportCallForm

User: Mesa, Kelsey

Kerberos: kmmesa

Full Error: Cannot read property 'dueDate' of null

Stack: TypeError: Cannot read property 'dueDate' of null
    at Object._supportCallResponseReducers (https://ipa.ucdavis.edu/js/instructionalSupportApp.js?rel=1492190481868:7:31528)
    at Object.reduce (https://ipa.ucdavis.edu/js/instructionalSupportApp.js?rel=1492190481868:8:176)
    at supportStaffFormService.getInitialState.then.$rootScope.$emit.message (https://ipa.ucdavis.edu/js/instructionalSupportApp.js?rel=1492190481868:7:20777)
    at processQueue (https://ipa.ucdavis.edu/js/lib.js:14:6272)
    at https://ipa.ucdavis.edu/js/lib.js:14:6539
    at Scope.$eval (https://ipa.ucdavis.edu/js/lib.js:14:19946)
    at Scope.$digest (https://ipa.ucdavis.edu/js/lib.js:14:17635)
    at Scope.$apply (https://ipa.ucdavis.edu/js/lib.js:14:20372)
    at https://ipa.ucdavis.edu/js/lib.js:14:13034
    at completeOutstandingRequest (https://ipa.ucdavis.edu/js/lib.js:11:8147)

**Comment by ltwheeler** [comment]
Issue has been resolved previously
