### ISSUE TITLE
AssignmentsView: Cannot read undefined

### ISSUE THREAD

**Issue by ltwheeler** [ucdavis/ipa-client-angular#1200]
URL: https://ipa.ucdavis.edu/assignments/69/2017?tab=courses

User: Hanou, Mandy

Kerberos: mhanou

Full Error: Cannot read property 'teachingAssignmentTermCodeIds' of undefined

Stack: TypeError: Cannot read property 'teachingAssignmentTermCodeIds' of undefined
    at Object._instructorReducers (https://ipa.ucdavis.edu/js/assignmentApp.js?rel=1502926136298:7:21071)
    at Object.reduce (https://ipa.ucdavis.edu/js/assignmentApp.js?rel=1502926136298:7:27958)
    at assignmentService.updateInstructorAssignment.then.$rootScope.$emit.message (https://ipa.ucdavis.edu/js/assignmentApp.js?rel=1502926136298:7:5575)
    at processQueue (https://ipa.ucdavis.edu/js/lib.js:14:6272)
    at https://ipa.ucdavis.edu/js/lib.js:14:6539
    at Scope.$eval (https://ipa.ucdavis.edu/js/lib.js:14:19946)
    at Scope.$digest (https://ipa.ucdavis.edu/js/lib.js:14:17635)
    at Scope.$apply (https://ipa.ucdavis.edu/js/lib.js:14:20372)
    at https://ipa.ucdavis.edu/js/lib.js:14:13034
    at completeOutstandingRequest (https://ipa.ucdavis.edu/js/lib.js:11:8147)

**Comment by ltwheeler** [comment]
Was able to replicate with a copy of production database:

In the support call, Roxanne Baker was assigned as an AI to a course,
which created a teachingAssignment as well.

When attempting to remove Roxanne Baker in the assignments view, the action succeeds but the UI breaks.

We need to ensure that changes on either the supportAssignment or teachingAssignment side of things, appropriately reflect in the other.
