### ISSUE TITLE
JS Error: Cannot set property 'sectionIds' of undefined at Object._sectionGroupReducers

### ISSUE THREAD

**Issue by cthielen** [ucdavis/ipa-client-angular#1405]
URL: https://ipa.ucdavis.edu/courses/11/2016 User: Louderman, Meshell Kerberos: mahays Full Error: Cannot set property 'sectionIds' of undefined Stack: TypeError: Cannot set property 'sectionIds' of undefined at Object._sectionGroupReducers (https://ipa.ucdavis.edu/js/courseApp.js?rel=1509399455537:8:3972) at Object.reduce (https://ipa.ucdavis.edu/js/courseApp.js?rel=1509399455537:8:10191) at courseService.getSectionsBySectionGroupId.then.$rootScope.$emit.message (https://ipa.ucdavis.edu/js/courseApp.js?rel=1509399455537:7:19993) at processQueue (https://ipa.ucdavis.edu/js/lib.js:14:6272) at https://ipa.ucdavis.edu/js/lib.js:14:6539 at Scope.$eval (https://ipa.ucdavis.edu/js/lib.js:14:19946) at Scope.$digest (https://ipa.ucdavis.edu/js/lib.js:14:17635) at https://ipa.ucdavis.edu/js/lib.js:14:20089 at completeOutstandingRequest (https://ipa.ucdavis.edu/js/lib.js:11:8147) at https://ipa.ucdavis.edu/js/lib.js:11:11273

**Comment by ltwheeler** [comment]
Unable to reproduce.

getSectionsBySectionGroupId is triggered in the courses view the first time you select a specific planned seats cell, or create a new sectionGroup, the sections are then used to render the sidebar.
The backend is properly written to complain if the sectionGroupId wasn't valid.

I made the state layer more defensive, will need to wait and see if it happens again.
