### ISSUE TITLE
SchedulingView: object doesn't support findIndex

### ISSUE THREAD

**Issue by ltwheeler** [ucdavis/ipa-client-angular#1437]
URL: https://ipa.ucdavis.edu/scheduling/12/2017/03 User: Sanchez, Mary Kerberos: emmie Full Error: Object doesn't support property or method 'findIndex' Stack: TypeError: Object doesn't support property or method 'findIndex' at _array_getIndexById (https://ipa.ucdavis.edu/js/sharedApp.js?rel=1510259909737:6:791) at _array_findById (https://ipa.ucdavis.edu/js/sharedApp.js?rel=1510259909737:6:684) at Term.prototype.getTermByTermShortCodeAndYear (https://ipa.ucdavis.edu/js/sharedApp.js?rel=1510259909737:6:19892) at Anonymous function (https://ipa.ucdavis.edu/js/schedulingApp.js?rel=1510259909737:6:8983) at processQueue (https://ipa.ucdavis.edu/js/lib.js:14:6255) at Anonymous function (https://ipa.ucdavis.edu/js/lib.js:14:6539) at Scope.prototype.$eval (https://ipa.ucdavis.edu/js/lib.js:14:19927) at Scope.prototype.$digest (https://ipa.ucdavis.edu/js/lib.js:14:17619) at Scope.prototype.$apply (https://ipa.ucdavis.edu/js/lib.js:14:20361) at Anonymous function (https://ipa.ucdavis.edu/js/lib.js:14:13023)

**Comment by cthielen** [comment]
This is occurring as of 11/16/17.
