### ISSUE TITLE
Scheduling view null error

### ISSUE THREAD

**Issue by ltwheeler** [ucdavis/ipa-client-angular#724]
URL: https://ipa.ucdavis.edu/scheduling/43/2017/10

User: Nofziger, Karen

Kerberos: gurley

Full Error: Cannot read property 'split' of null

Stack: TypeError: Cannot read property 'split' of null
    at activityToEvents (https://ipa.ucdavis.edu/js/schedulingApp.js:6:10931)
    at https://ipa.ucdavis.edu/js/schedulingApp.js:6:12933
    at Array.forEach (native)
    at sectionGroupToActivityEvents (https://ipa.ucdavis.edu/js/schedulingApp.js:6:12853)
    at getActivities (https://ipa.ucdavis.edu/js/schedulingApp.js:6:10123)
    at refreshCalendar (https://ipa.ucdavis.edu/js/schedulingApp.js:6:8793)
    at https://ipa.ucdavis.edu/js/schedulingApp.js:6:15104
    at Scope.$emit (https://ipa.ucdavis.edu/js/lib.js:14:21554)
    at Object.reduce (https://ipa.ucdavis.edu/js/schedulingApp.js:7:2995)
    at Object.setSelectedActivity (https://ipa.ucdavis.edu/js/schedulingApp.js:6:20617)

**Comment by ltwheeler** [comment]
Related to #734
