### ISSUE TITLE
Courses View: Undefined object 

### ISSUE THREAD

**Issue by ltwheeler** [ucdavis/ipa-client-angular#771]
URL: https://ipa.ucdavis.edu/courses/14/2017

User: Lade, Tracy

Kerberos: lade

Full Error: Object doesn't support property or method 'from'

Stack: TypeError: Object doesn't support property or method 'from'
   at Anonymous function (https://ipa.ucdavis.edu/js/courseApp.js:6:18948)
   at watchGroupAction (https://ipa.ucdavis.edu/js/lib.js:14:14316)
   at Scope.prototype.$eval (https://ipa.ucdavis.edu/js/lib.js:14:19927)
   at Scope.prototype.$digest (https://ipa.ucdavis.edu/js/lib.js:14:17619)
   at Scope.prototype.$apply (https://ipa.ucdavis.edu/js/lib.js:14:20361)
   at Anonymous function (https://ipa.ucdavis.edu/js/lib.js:14:13023)
   at completeOutstandingRequest (https://ipa.ucdavis.edu/js/lib.js:11:8144)
   at Anonymous function (https://ipa.ucdavis.edu/js/lib.js:11:11273)

**Comment by ltwheeler** [comment]
Cannot reproduce the issue. Will watch to see if the bug comes up again.
