### ISSUE TITLE
SupportStaffSupportCallForm: Cannot read property 'dueDate' of null

### ISSUE THREAD

**Issue by ltwheeler** [ucdavis/ipa-client-angular#944]
URL: https://ipa.ucdavis.edu/instructionalSupport/15/2017/201803/studentSupportCallForm

User: Rajamani, Anita

Kerberos: arajaman

Full Error: Cannot read property 'dueDate' of null

Stack: TypeError: Cannot read property 'dueDate' of null
    at Object._supportCallResponseReducers (https://ipa.ucdavis.edu/js/instructionalSupportApp.js?rel=1491835727869:7:27587)
    at Object.reduce (https://ipa.ucdavis.edu/js/instructionalSupportApp.js?rel=1491835727869:7:28322)
    at supportStaffFormService.getInitialState.then.$rootScope.$emit.message (https://ipa.ucdavis.edu/js/instructionalSupportApp.js?rel=1491835727869:7:17038)
    at processQueue (https://ipa.ucdavis.edu/js/lib.js:14:6272)
    at https://ipa.ucdavis.edu/js/lib.js:14:6539
    at Scope.$eval (https://ipa.ucdavis.edu/js/lib.js:14:19946)
    at Scope.$digest (https://ipa.ucdavis.edu/js/lib.js:14:17635)
    at Scope.$apply (https://ipa.ucdavis.edu/js/lib.js:14:20372)
    at https://ipa.ucdavis.edu/js/lib.js:14:13034
    at completeOutstandingRequest (https://ipa.ucdavis.edu/js/lib.js:11:8147)

**Comment by ltwheeler** [comment]
Issue has been resolved
