### ISSUE TITLE
registrarReconcilliationReport: undefined

### ISSUE THREAD

**Issue by ltwheeler** [ucdavis/ipa-client-angular#962]
URL: https://ipa.ucdavis.edu/registrarReconciliationReport/11/2017/10

User: Pham, Thao

Kerberos: tpham511

Full Error: Cannot convert undefined or null to object

Stack: TypeError: Cannot convert undefined or null to object
    at https://ipa.ucdavis.edu/js/registrarReconciliationReportApp.js?rel=1492190481872:6:27611
    at Array.forEach (native)
    at Object._sectionReducers (https://ipa.ucdavis.edu/js/registrarReconciliationReportApp.js?rel=1492190481872:6:27355)
    at Object.reduce (https://ipa.ucdavis.edu/js/registrarReconciliationReportApp.js?rel=1492190481872:6:30136)
    at reportService.updateActivity.then.$rootScope.$emit.message (https://ipa.ucdavis.edu/js/registrarReconciliationReportApp.js?rel=1492190481872:6:16069)
    at processQueue (https://ipa.ucdavis.edu/js/lib.js:14:6272)
    at https://ipa.ucdavis.edu/js/lib.js:14:6539
    at Scope.$eval (https://ipa.ucdavis.edu/js/lib.js:14:19946)
    at Scope.$digest (https://ipa.ucdavis.edu/js/lib.js:14:17635)
    at Scope.$apply (https://ipa.ucdavis.edu/js/lib.js:14:20372)

**Comment by ltwheeler** [comment]
Unable to reproduce with same database - will wait to see if the issue reoccurs
